/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#include <cassert>

int main() {
    TestProject_cpp::Greeter greeter;
    assert(greeter.greeting().compare("CPP Test Complete") == 0);
    return 0;
}
