/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include <Windows.h>

std::string TestProject_cpp::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    TestProject_cpp::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    system("pause");
    return 0;
}
