/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestProject_java;

public class App {
    public String getGreeting() {
        return "Java Test Complete";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
